version: '3.8'

services:
  frontend:
    build:
      context: ./KienTrucPhanMem_Nhom14_Client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://localhost:3000

  backend:
    build:
      context: ./KienTrucPhanMem_Nhom14/Server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./KienTrucPhanMem_Nhom14/Server/.env.development
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/n14shop
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=n14shop

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data: 